In [2]:
import numpy as np
#python list
py_list=[1,2,3,4,5,6]
#numpy list
np_array=np.array([1,2,3,4,5,6,7,8,9])
print(type(py_list))
print(type(np_array))
      

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
py_multi=[[1,2,3],[4,5,6],[7,8,9]]
np_multi=np_array.reshape(3,3)
print(py_multi)
print(np_multi)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(np_array.ndim)
print(np_multi.ndim)
#sahip oldugu eksen sayısını verır x ve y 

1
2


In [11]:
print(np_array.shape)
print(np_multi.shape)

(9,)
(3, 3)


In [12]:
result=np.array([1,2,3,4])
print(result)

[1 2 3 4]


In [13]:
result=np.arange(1,10)
print(result)

[1 2 3 4 5 6 7 8 9]


In [14]:
result=np.arange(1,10,3)
print(result)

[1 4 7]


In [15]:
result=np.zeros(10)
print(result)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
result=np.ones(10)
print(result)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [18]:
result=np.linspace(0,100,5)
print(result)
#Baslangic ve bitis aralıgını boler (5 tane sayı ) (4aralık)

[  0.  25.  50.  75. 100.]


In [20]:
result=np.random.randint(0,10) #10dahıl degıl
print(result)

1


In [22]:
result=np.random.randint(10)
print(result)
#bıtıs degerı max9

8


In [26]:
result=np.random.randint(0,10,5)
print(result)
#dizi dondurur 5 adet rasgele sayıyı iceren

[3 9 5 8 9]


In [27]:
result=np.random.rand(5)
print(result)
#0-5 arası rasgele sayı float da olur 

[0.34933984 0.29802058 0.97538178 0.12547632 0.48563224]


In [4]:
result=np.random.randn(5)
print(result)
#eksı degerlerde gelır

[ 1.17058843 -0.1235836  -1.07666398  1.22993142 -0.87294613]


In [29]:
np_array=np.arange(50)
result=np_array.reshape(5,10)
print(result)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [35]:
np_array=np.arange(50)
np_multi=np_array.reshape(5,10)
print(np_multi.sum(axis=1))
#satırların toplamı gelir
print(np_multi.sum(axis=0))
#sutunların toplamı gelır

[ 45 145 245 345 445]
[100 105 110 115 120 125 130 135 140 145]


In [40]:
rnd_numbers=np.random.randint(1,100,10)
print(rnd_numbers)
result=rnd_numbers.max()
print(result)
result=rnd_numbers.min()
print(result)
result=rnd_numbers.mean()
print(result)
result=rnd_numbers.argmax()#uretılen en buyuk sayının ındeksını
print(result)
result=rnd_numbers.argmin()#uretılen en buyuk sayının ındeksını
print(result)

[88 27 96 44 97 82 76 97 70 96]
97
27
77.3
4
1


In [47]:
numbers=np.array([0,5,10,15,20,25,50,75])
result=numbers[5]
print(result)
result=numbers[-1]
print(result)
result=numbers[0:3]
print(result)
result=numbers[:3]
print(result)
result=numbers[3:]
print(result)
result=numbers[::]
print(result)
result=numbers[::-1]
print(result)
result=numbers[::-2]
print(result)

25
75
[ 0  5 10]
[ 0  5 10]
[15 20 25 50 75]
[ 0  5 10 15 20 25 50 75]
[75 50 25 20 15 10  5  0]
[75 25 15  5]


In [62]:
numbers2=np.array([[0,5,10],[15,20,25],[50,75,85]])
print(numbers2)
print("****")
result=numbers2[0]
print(result)
result=numbers2[1]
print(result)
result=numbers2[0,2] #0.ındeks satırı 2.eleman
print(result)
result=numbers2[2,1]
print(result)
result=numbers2[:,2] #tum saatırlardan 2.ındeks sutunu
print(result)
result=numbers2[:,0]
print(result)
result=numbers2[:,0:2] #tum satırları sectık 0 ve 2. ındeks sutunlarındakı elemanları aldı ;
print(result)
result=numbers2[-1,:] #son satırdakı tum sutunları aldık
print(result)
result=numbers2[:3,:3] # tum satırlardan tum sutunları
print(result)
result=numbers2[:2,:2] # 2satıra kadar ve 2sutuna kadar olan elemanlar
print(result)

[[ 0  5 10]
 [15 20 25]
 [50 75 85]]
****
[ 0  5 10]
[15 20 25]
10
75
[10 25 85]
[ 0 15 50]
[[ 0  5]
 [15 20]
 [50 75]]
[50 75 85]
[[ 0  5 10]
 [15 20 25]
 [50 75 85]]
[[ 0  5]
 [15 20]]


In [63]:
arr1=np.arange(0,10)
arr2=arr1 #referans kopyalama
print(arr1)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [64]:
arr2[0]=20
arr2[0]=20
print(arr1)
print(arr2)

[20  1  2  3  4  5  6  7  8  9]
[20  1  2  3  4  5  6  7  8  9]


In [67]:
#farklı adreste kopyalama 
arr1=np.arange(0,10)
arr2=arr1.copy()

print(arr1)
print(arr2)
arr2[0]=20 #sadece arr2 yi etkıledi
print(arr1)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[20  1  2  3  4  5  6  7  8  9]


In [68]:
#numpy dizi operasyonları

In [69]:
numbers1=np.random.randint(10,100,6)
numbers2=np.random.randint(10,100,6)
print(numbers1)
print(numbers2)                   

[64 99 77 79 89 25]
[22 23 52 95 92 38]


In [71]:
result=numbers1+numbers2
print(result)

[ 86 122 129 174 181  63]


In [72]:
result=numbers1+10
print(result)

[ 74 109  87  89  99  35]


In [73]:
result=numbers1-numbers2
print(result)

[ 42  76  25 -16  -3 -13]


In [74]:
result=numbers1-10
print(result)

[54 89 67 69 79 15]


In [75]:
result=numbers1*numbers2
print(result)

[1408 2277 4004 7505 8188  950]


In [76]:
result=numbers1/numbers2
print(result)

[2.90909091 4.30434783 1.48076923 0.83157895 0.9673913  0.65789474]


In [77]:
result=numbers1/10
print(result)

[6.4 9.9 7.7 7.9 8.9 2.5]


In [80]:
result=np.sin(numbers1)
print(result)
result=np.cos(numbers1)
print(result)
result=np.sqrt(numbers1) #sqrt karekok
print(result)
result=np.log(numbers1)
print(result)

[ 0.92002604 -0.99920683  0.99952016 -0.44411267  0.86006941 -0.13235175]
[ 0.39185723  0.03982088 -0.03097503 -0.89597095  0.51017704  0.99120281]
[8.         9.94987437 8.77496439 8.88819442 9.43398113 5.        ]
[4.15888308 4.59511985 4.34380542 4.36944785 4.48863637 3.21887582]


In [81]:
mnumbers1=numbers1.reshape(2,3)
mnumbers2=numbers2.reshape(2,3)
print(mnumbers1)
print(mnumbers2) 

[[64 99 77]
 [79 89 25]]
[[22 23 52]
 [95 92 38]]


In [84]:
result=np.vstack((mnumbers1,mnumbers2)) #dıkey olarak art arda ekledı bırlestırdı
print(result)
result=np.hstack((mnumbers1,mnumbers2)) #yatay olarak art arda ekledı bırlestırdı
print(result)

[[64 99 77]
 [79 89 25]
 [22 23 52]
 [95 92 38]]
[[64 99 77 22 23 52]
 [79 89 25 95 92 38]]


In [93]:
#result=numbers1>=50
#print(result)
result=numbers1%2==0
print(result)
print(numbers1[result])

[ True False False False False False]
[64]


In [4]:
result=np.random.rand(10) # 0-1 arası 10 adaet sayı
print(result)
result=np.random.randn(10) # -1 ve 1 arası 10 adaet sayı
print(result)

[0.49131897 0.43016305 0.75193309 0.49786058 0.21730598 0.68829105
 0.52536928 0.01885299 0.10473497 0.35184531]
[ 0.54144697 -1.56711227 -0.47070244  1.20755466 -0.00292482  0.20631061
  1.1441379  -2.26706869  2.11981374  0.42877054]


In [99]:
result=np.random.randint(10,50,15).reshape(3,5)
print(result)

[[28 43 10 15 40]
 [35 29 27 26 49]
 [42 21 14 17 27]]


In [5]:
matris=np.random.randint(10,50,15).reshape(3,5)
toplamyatay=matris.sum(axis=1)
print(toplamyatay)
toplamdikey=matris.sum(axis=0)
print(toplamdikey)

[109 146 127]
[53 93 75 65 96]


In [6]:
matris=np.random.randint(-50,50,15).reshape(3,5)
result1=matris.max()
print(result1)
result=matris.min()
print(result)

43
10


In [7]:
arr=np.arange(10,20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [9]:
result=arr[::]
print(result)

[10 11 12 13 14 15 16 17 18 19]


In [12]:
ciftler=matris[matris%2==0]
result=ciftler[ciftler>15]
print(result)

[30 34 22 34 20]
